name: Run Playwright Tests and Publish Report

on:
  push:
    branches: [main]
  workflow_dispatch:  # Manual trigger

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run Playwright tests
        run: npx playwright test --reporter html

      - name: Upload HTML report artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: playwright-report
          path: playwright-report/

  deploy-report:
    needs: test
    if: ${{ success() }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download report artifact
        uses: actions/download-artifact@v3.1.3
        with:
          name: playwright-report
          path: playwright-report

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: playwright-report
